'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class projectsProjectDetail
    
    '''<summary>
    '''litBreadcrumb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBreadcrumb As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litProjName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litProjName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litErrorInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litErrorInfo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litStage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStage As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblSector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSector As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''geoFocus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents geoFocus As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''locationDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents locationDetail As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLocation As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Description As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblPCo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPCo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''instrumentalOrgs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents instrumentalOrgs As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ghgYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ghgYears As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ghgasreduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ghgasreduction As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ghgFor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ghgFor As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litResults As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''phAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phAttachments As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lblPC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPC As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblFIK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFIK As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''Comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Comments As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litExpo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litExpo As Global.System.Web.UI.WebControls.Literal
End Class
