'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class index6

    '''<summary>
    '''emailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''organization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents organization As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''jobTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jobTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents country As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Removedcountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Removedcountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''organizationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents organizationType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''referral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents referral As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTextBox As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''referralOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents referralOther As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''experience control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents experience As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''register control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents register As Global.System.Web.UI.WebControls.Button
End Class
