'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class oil_gas_index
    
    '''<summary>
    '''phupcomingevents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phupcomingevents As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''upcomingevents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upcomingevents As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''coalevents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coalevents As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''recentevents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recentevents As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''phChairs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phChairs As Global.System.Web.UI.WebControls.PlaceHolder
End Class
