'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class homeBannerEdit

    '''<summary>
    '''hfBannerId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfBannerId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtBannerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBannerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMainText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMainText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSubText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtButtonText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButtonText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtButtonDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButtonDestination As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlBannerStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBannerStyle As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imageSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imageSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''fuImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuImage As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''txtAltText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAltText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gradientSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gradientSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rbGradients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbGradients As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
