'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class resources_details

    '''<summary>
    '''resource_details_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resource_details_form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''LitResourceLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LitResourceLink As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''videowrapper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents videowrapper As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''videoWrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents videoWrp As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''resourceFileFrame control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resourceFileFrame As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''videoPlaceholder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents videoPlaceholder As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''phresourceDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phresourceDetails As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''rightSidebar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rightSidebar As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''phresourceDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phresourceDescription As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''litResourceOptionNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litResourceOptionNumber As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''phEventList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phEventList As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''phRelatedResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phRelatedResources As Global.System.Web.UI.WebControls.PlaceHolder
End Class
