'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class reloadresources
    
    '''<summary>
    '''resources_index_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resources_index_form As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''litTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''loading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loading As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''phResourceList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phResourceList As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''allresources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents allresources As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
