'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class projectNetwork

    '''<summary>
    '''form2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form2 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''KPI1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KPI1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PieChart1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PieChart1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''KPI2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KPI2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PieChart2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PieChart2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''CountsPNOrganizationsActiveContactsPrivate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountsPNOrganizationsActiveContactsPrivate As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''CountsPNOrganizationsActiveContactsResearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountsPNOrganizationsActiveContactsResearch As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''CountsPNOrganizationsActiveContactsGov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountsPNOrganizationsActiveContactsGov As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''CountsPNOrganizationsActiveContactsFinancialInstitutions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountsPNOrganizationsActiveContactsFinancialInstitutions As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''CountsPNOrganizationsActiveContactsNonGov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountsPNOrganizationsActiveContactsNonGov As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''CountsPNOrganizationsActiveContactsOthers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountsPNOrganizationsActiveContactsOthers As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvComms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvComms As Global.System.Web.UI.WebControls.GridView
End Class
