'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class register2

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''firstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''jobTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jobTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''organization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents organization As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''orgType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents orgType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents country As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''areaOfInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaOfInterest As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''posterPicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents posterPicker As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''aoiProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aoiProjects As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''aoiProjectsOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aoiProjectsOther As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''attendanceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attendanceType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''IPmondayUNECE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPmondayUNECE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IPmondayBiogas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPmondayBiogas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IPmondayCoal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPmondayCoal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IPmondayGMI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPmondayGMI As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IPtuesdayPlenary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPtuesdayPlenary As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IPwednesdayCoal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPwednesdayCoal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IPwednesdayBiogas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPwednesdayBiogas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IPwednesdayOilGas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPwednesdayOilGas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IPthursdayUNECE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPthursdayUNECE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IPmondayReception control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPmondayReception As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''IPtuesdayReception control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IPtuesdayReception As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''VmondaySteering control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VmondaySteering As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''VmondayBiogas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VmondayBiogas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''VtuesdayPlenary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VtuesdayPlenary As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''VwednesdayBiogas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VwednesdayBiogas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optOutCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optOutCheck As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submit As Global.System.Web.UI.WebControls.Button
End Class
