'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class comms_add

    '''<summary>
    '''subjectLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subjectLine As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''msgURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgURL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''areaOfInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaOfInterest As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''language control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents language As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dateSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateSent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''contacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contacts As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''subscribers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subscribers As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''openRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents openRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''clickRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clickRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bounceRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bounceRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''unsubRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents unsubRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Add As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvComms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvComms As Global.System.Web.UI.WebControls.GridView
End Class
