'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class lgdocReview
    
    '''<summary>
    '''LargeDocReviewForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LargeDocReviewForm As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''LgattachmentActDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LgattachmentActDownload As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LgattachmentAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LgattachmentAct As Global.System.Web.UI.WebControls.Literal
End Class
