'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class resource_create

    '''<summary>
    '''resourceCreateform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resourceCreateform As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''rblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblStatus As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pnlParentResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlParentResource As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlParentNameInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlParentNameInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtResourceParentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResourceParentID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlNameInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNameInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlAuthorInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAuthorInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''author control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents author As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlShortNameInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShortNameInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''shortname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents shortname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlGroupingInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGroupingInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grouping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grouping As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HideNotes1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HideNotes1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Show1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Show1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlLanguages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLanguages As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''infoPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infoPages As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''infoDocType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infoDocType As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''infotopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infotopic As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlTopics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTopics As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''libTopics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents libTopics As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''ResourceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResourceType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''plnResourceUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plnResourceUpload As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''urlPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents urlPath As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''resourceImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resourceImage As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''pnlResourceDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResourceDetails As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlResourceInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResourceInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtResourceImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResourceImage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgresourceImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgresourceImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnDeleteFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteFile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateInfo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''infoRelRes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infoRelRes As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvRelatedResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRelatedResource As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnSave4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSave6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave6 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSave3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave3 As Global.System.Web.UI.WebControls.Button
End Class
