'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class country_v2

    '''<summary>
    '''pnlCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCategory As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''categoryFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoryFilter As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''LitExportSQL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LitExportSQL As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tab7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tab7 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ActionPlansLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionPlansLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''tab8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tab8 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SubcommitteeLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubcommitteeLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tab1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ActivitiesLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivitiesLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LitactivityCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LitactivityCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tab2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ToolsResourcesLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolsResourcesLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LitresourcesCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LitresourcesCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tab3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tab3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EventLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LiteventCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteventCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tab5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tab5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MembersLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MembersLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LitpartnerCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LitpartnerCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnExportToExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportToExcel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchResults As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''searchExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchExport As Global.System.Web.UI.WebControls.GridView
End Class
