'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class activities
    
    '''<summary>
    '''activities_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents activities_form As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''litTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''phActivityList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phActivityList As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''allactivities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents allactivities As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''coalactivities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coalactivities As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''biogasactivities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents biogasactivities As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''oilgasactivities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oilgasactivities As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''reloadActivities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reloadActivities As Global.System.Web.UI.WebControls.LinkButton
End Class
