'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class events_index

    '''<summary>
    '''events_index_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents events_index_form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''phUpcomingEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phUpcomingEvents As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''phRecentEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phRecentEvents As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''draftevents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents draftevents As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''phDraftEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phDraftEvents As Global.System.Web.UI.WebControls.PlaceHolder
End Class
