'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class events_details_test
    
    '''<summary>
    '''eventdetailsform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eventdetailsform As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''pheventhead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pheventhead As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''pheventsummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pheventsummary As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''pheventdetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pheventdetails As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''resourcerow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resourcerow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''phrelatedresources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phrelatedresources As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''phRelatedEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phRelatedEvents As Global.System.Web.UI.WebControls.PlaceHolder
End Class
