'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class step2
    
    '''<summary>
    '''ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''actiontitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actiontitle As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BioGasCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BioGasCheck As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CoalMinesCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoalMinesCheck As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''OilGasCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OilGasCheck As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''activitylocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents activitylocation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''partners control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents partners As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''activityinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents activityinfo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''outcomes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents outcomes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''nextsteps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nextsteps As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LastStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastStep As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''NextStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NextStep As Global.System.Web.UI.WebControls.Button
End Class
