'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class resources_filtered
    
    '''<summary>
    '''resources_filteredForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resources_filteredForm As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''LitBreadcrumb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LitBreadcrumb As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlSearchCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearchCriteria As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LitSearchCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LitSearchCriteria As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''btnClearSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClearSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''srcStr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcStr As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''results1head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents results1head As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''PHfeaturedresources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PHfeaturedresources As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''topicLinksRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topicLinksRepeater As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''parentRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parentRepeater As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnltopicFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnltopicFilter As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chktopicFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chktopicFilter As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''pnlSectorFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSectorFilter As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chksectorFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chksectorFilter As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''pnlRegionFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRegionFilter As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkregionFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkregionFilter As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''pnlCountryFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCountryFilter As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''countryFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents countryFilter As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''dsTopicCheckboxList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTopicCheckboxList As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsCountryCheckboxList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCountryCheckboxList As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsRegionCheckboxList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsRegionCheckboxList As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsSectorCheckboxList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsSectorCheckboxList As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
