'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class resources
    
    '''<summary>
    '''resources_filteredForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resources_filteredForm As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''LitLastBreadcrumb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LitLastBreadcrumb As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''PHfeaturedresources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PHfeaturedresources As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''topicRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topicRepeater As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''sectorRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sectorRepeater As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''countryRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents countryRepeater As Global.System.Web.UI.WebControls.Repeater
End Class
